version: "3.8"
services:
    exporter:
        build:
            context: ./temp-exporter
            dockerfile: Dockerfile.exporter
        image: exporter:0.1
        restart: on-failure
        expose:
            - "8612"
        environment:
            - WE_APIKEY=${WE_APIKEY}
            - WE_CITY=${WE_CITY}
    prometheus:
        image: prom/prometheus
        depends_on:
            - exporter
        restart: on-failure
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - /PROMETHEUS:/prometheus:rw
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        restart: on-failure
        ports:
          - "3000:3000"
        environment:
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/dashboards/temperature-dashboard.json
        volumes:
          - ./grafana/provision-datasources.yml:/etc/grafana/provisioning/datasources/provision-datasources.yml:ro
          - ./grafana/provision-dashboards.yml:/etc/grafana/provisioning/dashboards/provision-dashboards.yml:ro
          - ./grafana/temperature-dashboard.json:/etc/dashboards/temperature-dashboard.json:ro
