version: "3.8"
services:
    exporter:
        build:
            context: ./temp-exporter
            dockerfile: Dockerfile.exporter
        image: exporter:0.1
        expose:
            - "8612"
        environment:
            - WE_APIKEY=${WE_APIKEY}
            - WE_CITY=${WE_CITY}
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - /PROMETHEUS:/prometheus:rw
    grafana:
        image: grafana/grafana
        ports:
          - "3000:3000"
       environment:
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/dashboards/temperature-dashboards.json          
        volumes:
          - ./grafana/provision-datasources.yml:/etc/grafana/provisioning/datasources/provision-datasources.yml:ro
          - ./grafana/provision-dashboards.yml:/etc/grafana/provisioning/dashboards/provision-dashboards.yml:ro
          - ./grafana/temperature-dashboards.json:/etc/dashboards/temperature-dashboards.json:ro
