version: "3.8"
services:
    exporter:
        build:
            context: ./temp-exporter
            dockerfile: Dockerfile.exporter
        image: exporter:my
        #expose:
        #    - "8612"
        ports:
            - "8612:8612"
        environment:
            - WE_APIKEY=${WE_APIKEY}
            - WE_CITY=${WE_CITY}
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
            - /tmp/promdb:/prometheus:rw
