# # config file version
apiVersion: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
#   # <string, required> name of the datasource. Required
 - name: Prometheus
   type: prometheus
   orgId: 1
   url: http://prometheus:9090
   editable: false
